### ISSUE TITLE
Cannot run tests

### ISSUE THREAD

**Issue by peastman** [fabriceci/Godot-Physics-Tests#9]
When I try to launch the tests, it fails at this line

https://github.com/fabriceci/Godot-Physics-Tests/blob/0a30c2be92b2a5701eb9b68e2e6c2ac7e162ba77/start.gd#L4

with the message

> "Parser Error: "TestRunner" was not found in the current scope.

I built Godot from the most recent code in the master branch.

**Comment by fabriceci** [comment]
@peastman I think there was a change in the project.godot (see https://github.com/fabriceci/Godot-Physics-Tests/commit/2f9a1f52c4b110e57ac5a920db5bd233409bf487) that corrupted the cache folder.

Can you delete the `.godot/` folder and try again?

**Comment by peastman** [comment]
That fixed it, thanks.
